# This is a basic workflow to help you get started with Actions

name: AutoBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置版本号
      - name: Set version
        id: set_version
        run: |
          # 获取最新标签，如果不存在则使用默认值 1.0.0
          VERSION=$(git describe --tags --abbrev=0 || echo "1.0.0")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      # 3. 打包代码为 ZIP 文件
      - name: Create ZIP archive
        run: |
          zip -r release.zip . -x '.git/*' -x '.github/*'
          echo "ZIP file created: release.zip"

      # 4. 创建 GitHub Release 并上传 ZIP 文件
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip  # 上传的 ZIP 文件
          tag_name: ${{ env.VERSION }}  # 使用 VERSION 变量作为标签
          generate_release_notes: true  # 自动生成 Release 说明
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}