# This is a basic workflow to help you get started with Actions

name: AutoBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. 检出代码
      - uses: actions/checkout@v4

      - name: Set version
        id: set_version
        run: echo "VERSION=1.0.0" >> $GITHUB_ENV  # 设置 VERSION 环境变量
      - name: Use version
        run: echo "Version is ${{ env.VERSION }}"  # 访问 VERSION 变量
      
      # 2. 打包代码为 ZIP 文件
      - name: Create ZIP archive
        run: |
          zip -r release.zip . -x '.git/*' -x '.github/*' 
          echo "ZIP file created: release.zip"

      # 3. 获取当前版本号（可选）
      - name: Get version
        id: get_version
        run: |
          echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV  # 获取最新标签作为版本号
          echo "Using version: $VERSION"

      # 4. 创建 GitHub Release 并上传 ZIP 文件
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip  # 上传的 ZIP 文件
          tag_name: ${{ env.VERSION }}  # 使用标签作为 Release 版本号
          generate_release_notes: true  # 自动生成 Release 说明
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 token
